services:
  onboarder:
    container_name: ebsi-onboarder-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/home/app
